apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podnoone
  name: podnoone
spec:
  containers:
  - image: nginx
    name: podnoone
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
