# 2022 version
apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    project: qsk-book
spec:
  containers:
    - name: web-ctr
      image: nigelpoulton/qsk-book:latest
      ports:
        - containerPort: 8080
